### ISSUE TITLE
Regression in text.open of a nonexistent file in BASIC! v01.84

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#173]
As initially spotted by tomverhoef in http://rfobasic.freeforums.org/syntax-error-on-text-open-t2870.html
there is a regression in `text.open r, fid, "nonexistent_file.txt"`.

The wanted behaviour, and actual behaviour in BASIC! < v01.84 was (as taken from the manual): `if a file being opened for read does not exist then the <file_table_nvar> will be set to -1`

The new (incorrect) behaviour in BASIC! v01.84 is the throw of a **java.lang.NullPointerException** in the Editor, and the throw of a **Syntax Error** (?) in APK mode.

**Comment by jMarcS** [comment]
Released in v01.85, 2015/02/15.
