### ISSUE TITLE
IS_IN() enhancement: reverse search

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#176]
Hello Marc,

This is the current form of IS_IN():
```
IS_IN(<sub_sexp>, <base_sexp>{, <start_nexp>})
```

I recently had the need of a reverse (right-to-left) search in BASIC! so I made one. The IS_IN() enhancement I propose is to take a negative `<start_nexp>` in order to do a right-to-left search. This way it doesn't break retro-compatibility. 

FYI this enhancement is inspired by PowerBasic INSTR function, see https://www.powerbasic.com/support/help/pbcc/instr_function.htm
(I find PowerBasic string operation functions really greatly designed)

Here is the new code (compiled, tested). Can it be added to the next release of BASIC! ?
```Java
	private boolean executeMF_IS_IN() {
		String[] args = getArgsSS();
		if (args == null) return false;
		String searchFor = args[0];
		String searchIn = args[1];

		if (isNext(',')) { if (!evalNumericExpression()) return false; }
		int start = EvalNumericExpressionValue.intValue();

		Boolean reverseSearch = (start < 0);
		if (reverseSearch) {
			start = start + searchIn.length(); }
		else {
			start--; }										// make start index zero-based

		int i1, k;
		if (start <= searchIn.length()) {					// if starting inside the string
			if (reverseSearch) {
				k = searchIn.lastIndexOf(searchFor, start);		// do the reverse search
				i1 = k + 1;									// make result one-based
			} else {
				k = searchIn.indexOf(searchFor, start);		// do the search
				i1 = k + 1;									// make result one-based
			}
		} else {
			i1 = 0;											// else "not found"
		}
		EvalNumericExpressionValue = (double)i1;
		return true;
	}
```

**Comment by jMarcS** [comment]
Released in v01.85, 2015/02/15.
