### ISSUE TITLE
cannot begin a variable with "time"

### ISSUE THREAD

**Issue by vnelson5** [RFO-BASIC/Basic#186]
I found that a variable name cannot begin with "time" such as:

timeattap=clock()/1000

returns a 0

tattap=clock()/1000

returns a valid result

**Comment by RFO-BASIC** [comment]
Time is a command. To avoid the problem:
LET time= x

**Comment by JeffLaun** [comment]
I am also found this problem that timexyz if not a valid variable name, although your GPS sample program uses time as a variable

**Comment by RFO-BASIC** [comment]
Time is a command. To avoid the problem:
LET time= x

**Comment by JeffLaun** [comment]
I do understand the "LET" workaround, sounds like bad programming to use reserved words as variables.  
Also weird that "timeXYZ = 5" is viewed as a conflict with the time command as the variable is not "time".  Thanks for the prompt response.  I am loving RFO-Basic.

**Comment by jMarcS** [comment]
Hi, JeffLaun. I'm not sure if there's a question here.

You do make a couple of statements that I believe are based on mistaken assumptions.
My short replies:

- Using `LET` is not a workaround. *Not* using `LET` is a shortcut.
- The "conflict" between `timeXYZ` and `time` is "weird" only if you assume words are always separated by something, like spaces. BASIC! does not require separators.

For more complete explanations, read on.

BASIC! syntax is very well-defined. In some aspects it is different from many other languages. That doesn't make it wrong. Some users dislike this particular feature you're talking about, for pretty much the same reasons you've stated. That doesn't make it wrong, either, but it has been discussed quite a few times in the user forum, http://rfobasic.freeforums.org. I recommend you join us there to see what other people have to say.

To summarize BASIC!'s rules about words:
- Outside of quotes, BASIC! ignores spaces and case. `my var = 1` and `MyVar=1` are exactly the same, defining a single variable named `myvar`.
- BASIC! always looks for a command keyword at the beginning of a statement. If you put a variable there, it assumes the command is `LET`, and if you put a function name there, it assumes the command is `CALL`.
- BASIC! does not look for a keyword in an expression, except for some well-defined special cases like `THEN` after `IF` or `TO` after `FOR`.

Pretty simple, right? So if you put a variable called `timeXYZ` at the beginning of the line, the interpreter is not looking for a variable name. It's looking for a command keyword, and it finds one: `time`. At the beginning of the line, `time` is a keyword regardless of what follows it.

`TIME xyz` is a valid BASIC! statement: it extracts the time components of the number in `xyz` and discards them. `timeXYZ` is exactly the same statement.

On the other hand, if you put a variable called `timeXYZ` in an expression, such as `t = timeXYZ + offset`, then `timeXYZ` is a valid variable name. The interpreter is not looking for a command keyword, so it finds the variable name `timeXYZ`. It finds that variable name even if you embed spaces for readability, as in `t = time XYZ + offset`.

Now that you know the rules, you should understand that using `LET` is not a workaround. When you said that, you assumed `variable = value` is a normal BASIC! line. Now you know that it is not. There's no command there. Normal BASIC! would be `LET variable = value`. The interpreter does you a favor by allowing you a shortcut: the command LET is implied.

You said it's "bad programming to use reserved words as variables". BASIC! does not use reserved words as variables. It looks for command keywords in some contexts and variable names in others. The contexts are very easy to tell apart, and they are explained completely in the manual.

BASIC! allows you to use command keywords as variables if you want to. You can decide for yourself whether doing so is bad programming. If you decide that it is bad programming, then BASIC! gives you tools to help you find places where you use these "bad" variables by mistake.

Does that help? Is there something else I can try to explain?
