### ISSUE TITLE
A sinple request: Make the "Run" entry appear on the action bar in Android 4.0+

### ISSUE THREAD

**Issue by Akmal02** [RFO-BASIC/Basic#187]
Please add the following line in the "res/menu/main.xml"

 android:showAsAction="ifRoom"

in the run item entry.

It makes the "Run" menu appear in the action bar instead in the menu list.

Is it more convenient to launch it on single tap instead on two taps? So far it works on Android 4.0+, don't know in the earlier version.
Thanks in advance.

**Comment by jMarcS** [comment]
I was unaware of this option. Thank you!

It can't be done quite as simply as you suggest. You like "Run" on the action bar, but somebody else might not. And what happens on devices that don't have an action bar?

What I did was to add a section to the Preferences screen labeled, "Menu Items on Action Bar". In the sub-menu, it offers independent checkboxes for RUN, LOAD, SAVE, and EXIT. Similar options can be added for any menu item, if somebody wants them.

When the Editor starts or restarts (`onResume()`), it checks the Preferences and (re)builds the menu and action bar as indicated. You can select as many items as you want, but the number displayed depends on the device and the orientation. There is no provision for changing the order in which items are displayed.

On devices with API levels earlier than 11, the Preferences are available, but they have no effect on the menu.

**Comment by jMarcS** [comment]
Released in v01.88, 2015/08/16.
