### ISSUE TITLE
Cannot register for forum at rfobasic.free forums.org

### ISSUE THREAD

**Issue by willsheppard** [RFO-BASIC/Basic#189]
I want to post a programming question but I can't register!

There is an error in the "Confirmation code" box:

    client error 117B

At http://rfobasic.freeforums.org/ucp.php?mode=register

Could an admin please get it fixed so we can register for the forum? Thanks

(tried on Android)

**Comment by jMarcS** [comment]
I don't have direct control of the registration process, but i checked all the settings I can see and everything looks ok. So I tried registering a bogus user, and that went ok, too. Some of the process is a bit annoying, but I don't control that, either.

I did the registration on an Android tablet, but I was using "full style", not "mobile style". That should not matter, but it is something you could try.

I figure you ran into a temporary problem. Try again, please. If you still have trouble, post here again and I'll contact free forums.org tech support.

**Comment by willsheppard** [comment]
@jMarcS you were right, I could register fine from my laptop. I guess this is something the freeforums.org people need to look at. Thanks
