### ISSUE TITLE
AJAX (jQuery) doesn't work anymore with latest Webview component

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#196]
With the latest Android System Webview (version 45.0.2454.95) the GW library, based on jQuery Mobile, doesn't work anymore, even when using GW_FORCE_MODE(1) i.e. dumping the html/js to a file and HTML.LOAD.URL it (reminder: GW_FORCE_MODE is explained here: http://rfobasic.freeforums.org/post16650.html#p16650 so far it always solved the blank screen, now not anymore with webview 45.0.2454.95)

Bug reported by forum user apeine at http://rfobasic.freeforums.org/post23482.html#p23482

**Comment by jMarcS** [comment]
I'm working on a new bug in v01.88 that changes the timing relationships when transitioning from one screen to another; the partial fix in v01.88.01 was not enough.

Have you confirmed that the bug you are seeing is due to the WebView change and not to the BASIC! change? Does it happen with the new WebView and old BASIC! (like v01.87)?

**Comment by mougino** [comment]
Yes I confirm. Same bug with BASIC! 1.87 and webview 45.0.2454.95

**Comment by jMarcS** [comment]
Thank you. That's bad news but good information.

**Comment by mougino** [comment]
More information: I narrowed down the regression to the switch from Android System WebView 44.0.2403.117 (working ok) to the next one 45.0.2454.19 (gray circle issue).
These versions can be downloaded for test purpose at http://www.apkmirror.com/uploads/?app=android-system-webview

**Comment by mougino** [comment]
Finally I found a fix!

The WebView bug can be solved with a simple piece of javascript added to the page at a certain place.

See forum post http://rfobasic.freeforums.org/post25519.html#p25519 for detail.

Marc, did you reactivate the hardware acceleration in Html view since we found it's not effective to solve this issue? We need it back in v01.89 (among other for video playback in Html page).

**Comment by jMarcS** [comment]
Excellent! I was making no headway at all, so I am glad you succeeded.

Hardware acceleration for the Html view is back on for v01.89. The change was in that commit on December 16.

**Comment by mougino** [comment]
Thank you Marc. So I can close this issue!
