### ISSUE TITLE
Command to block or let pass key-press to system

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#204]
As per user Aat request at http://rfobasic.freeforums.org/bluetooth-remote-control-t3939.html

He would like to be able to prevent a volume key-press to pass "volume +/-" info to the system.

We made volume info pass to Android system in issue #9 (opened in 2012, wow) here Aat would be interested to make this change configurable. He proposes the following syntax:
```
INKEY$ <svar>, <n_flag>
```
n_flag omitted or 0 - pass command through
n_flag >0 - block passing through of command

This would imply use of yet another global variable (array) in `Run.java` I'm afraid... How do you think?

**Comment by jMarcS** [comment]
Released in v01.90, 2016/03/31.
