### ISSUE TITLE
Possible Unnecessary Code Duplication

### ISSUE THREAD

**Issue by agrellum** [RFO-BASIC/Basic#210]
BluetoothChatService.java:301:            mmServerSocket = tmp;
BluetoothChatService.java:302:            mmServerSocket = tmp;

Format.java:85:		lv.setTextFilterEnabled(false);
Format.java:86:		lv.setTextFilterEnabled(false);

**Comment by jMarcS** [comment]
Good catch, agrellum. Thank you. I'll take out the duplicates for v01.90. I hope this means you're looking for ways to improve how BASIC! works.

**Comment by jMarcS** [comment]
Released in v01.90, 2016/03/31.
