### ISSUE TITLE
Nicer error handling when DECODE$() has wrong password

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#213]
As asked here: http://rfobasic.freeforums.org/bad-decode-not-throwing-runtime-error-t4184.html

I will propose an enhancement.

How do you want to do Marc? Should I push to my local repo and create a pull request?

**Comment by mougino** [comment]
My modifications are ready and tested, I am confident the changes are relatively safe.
Marc, tell me how you want we proceed next?

**Comment by jMarcS** [comment]
Nicolas, I think you are a collaborator on the project, so you can commit directly to the master branch. If you don't want to do that, create a pull request and I'll process it.
Same comment for issue 214.

**Comment by jMarcS** [comment]
Released in Version 01.91, 2017/03/14
