### ISSUE TITLE
RUN "" crashes BASIC!

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#216]
Calling RUN with empty string as a parameter crashes BASIC! with a null pointer exception on `BufferedReader.readLine()` called from `Basic.loadProgramFileToList()`.

See [related post in the forum](http://rfobasic.freeforums.org/post32627.html#p32627)

I have a very simple fix (1 line), in `Run.executeRun()`, that I will try to release with the new RUN enhancement (which is restarting the current program if called without parameter, goes along with the new `PROGRAM.PATH <runningBas_svar>` command).

**Comment by jMarcS** [comment]
If I understand, the fix is to report syntax error if RUN with an empty string. That's good, much better than crashing. But what happened to the proposal to or RUN with no parameter or a blank parameter re-run the current program?

**Comment by mougino** [comment]
This is addressed in issue #218 ;)

**Comment by jMarcS** [comment]
Released in Version 01.91, 2017/03/14
