### ISSUE TITLE
Audio.load command do not support URLS as file source.

### ISSUE THREAD

**Issue by JanuszChmiel** [RFO-BASIC/Basic#222]
Dear developers, It would be good start to implement live audio support. First of all, according to my opinion it would be very good start to implement this by modifying run.java. 
Good example of usage Android media player component is here:
		mp.setAudioStreamType(AudioManager.STREAM_MUSIC);
		try {
			mp.setDataSource(url);
More detailed info here:
https://developer.android.com/guide/topics/media/mediaplayer.html
Sure, it is necessary to decide when audio.load Basic command will open local file, when user will specify path and when user will add URL to open audio file. & character would be good solution to inform Basic interpreter, that user want to add URL. Audio.load must give The file The necessary index number. So audio.play will be able to play live stream. Please do not put this issue away, I think it well for Basic project.

**Comment by mougino** [comment]
This is done on my side, very small change, less than 10 lines of Java. I tested and it works very good, the only (small) downsize is a latency when opening the stream with `AUDIO.LOAD` (~12s in 3G+ with url http://amp1.cesnet.cz:8000/cro1.ogg).

I will push the change this week-end. The modification of the manual is easy too, we can mention this for example:

> Loads a music file or internet stream into the Audio File Table. The AFT index is returned in <aft_nvar>. If the file or stream can’t be loaded, the <aft_nvar> is set to 0. Your program should test the AFT index to find out if the audio was loaded. If the ~~bitmap pointer~~ AFT index is 0, you can call the GETERROR$() function to get information about the error. If you use index 0 in another Audio command you will get a run-time error.
> If you load a file it must be in the "<pref base drive>/ref-basic/data/" directories or one of its subdirectories.
> You can reach outside the "<pref base drive>/ref-basic/data/" by using path fields in the filename. For example, "../../Music/Blue Danube Waltz.mp3" would access "<pref base drive>/Music/Blue Danube Waltz.mp3".

NB: Note the incorrect mention of ~~bitmap pointer~~ in current manual: it needs to be changed to AFT index.

**Comment by JanuszChmiel** [comment]
Dear MR mougino,
Thank You very much for yours solution. I Am ready to test yours github changed code. Did you modified run.java module to add this support? .ogg streams are not easy for ANdroid media player to encode, and decompres. It is better to wait some seconds that having too short buffer. So thank You very much for yours support. I will have The chance to create my Internet radio player app by using Select command. It is better than handling HTML engine, which is memory intensive. Very well done and thank you again.

**Comment by JanuszChmiel** [comment]
Dear Nicolas,
I can not play live stream.
By using latest Rfo-basic. I have compiled it.
I have used following code.
Audio.load n,"http://amp1.cesnet.cz:8000/cro1.ogg"
Audio.play n 

But there is no play, no sound. No error, empty window, but no sound at all. I have tried to run in interpreter mode and also in APK mode. I have tried to enable all permissions including hardware acceleration. It do not work. I Am working with it by using WIFI fast connection. Does it really work?

**Comment by JanuszChmiel** [comment]
Dear Nicolas,
I Am very sorry, I have been used wrong algorithm.
Yours modiffication is working perfectly.
Here is good code adapted from manual.
Audio.load n,"http://amp1.cesnet.cz:8000/cro1.ogg" 
Audio.play n 
WakeLock 1 
Do 


Pause 30000 
Until 0 

Very well done and thank You very much for yours time and patience.

**Comment by JanuszChmiel** [comment]
Dear Nicolas,
I can make nicely looking GUIS thanks to yours library.
I have one strange plea.
How can I determine The ideal long of texts so text will look nicely on 
many various Android screens?
How to know, how many characters type in every
GW_ADD_TEXT(page,
Command so text will look nicely? Or Webwiev format text automatically 
to look nicely?
Yours library is perfect. I Am only sad, that I do not know which 
command should I use to load Gw so silently like while using Yours compiler?
Screen reader detect message loading lib. But yours compiler is 
containing some commands so screen reader do not detect this message, it 
is better.
Yours library is really excellent.
Yours compiler also. it produces smaller and reliable code.
Really very well done.


---
Tato zpráva byla zkontrolována na viry programem Avast Antivirus.
https://www.avast.com/antivirus

**Comment by mougino** [comment]
Hi Janusz, this is not the good place to ask for GW tips.
Can you create a topic at rfobasic.freeforums.org/gw-lib-f27.html ?
I'll gladly answer there

**Comment by olimaticer** [comment]
Dear Janusz,


You are right, only my test version do that.
Do you feel comfortable with this function?


/Gregor


________________________________
Von: JanuszChmiel <notifications@github.com>
Gesendet: Donnerstag, 16. März 2017 11:18
An: RFO-BASIC/Basic
Cc: Subscribed
Betreff: Re: [RFO-BASIC/Basic] Audio.load command do not support URLS as file source. (#222)

Dear Nicolas,
I can make nicely looking GUIS thanks to yours library.
I have one strange plea.
How can I determine The ideal long of texts so text will look nicely on
many various Android screens?
How to know, how many characters type in every
GW_ADD_TEXT(page,
Command so text will look nicely? Or Webwiev format text automatically
to look nicely?
Yours library is perfect. I Am only sad, that I do not know which
command should I use to load Gw so silently like while using Yours compiler?
Screen reader detect message loading lib. But yours compiler is
containing some commands so screen reader do not detect this message, it
is better.
Yours library is really excellent.
Yours compiler also. it produces smaller and reliable code.
Really very well done.


---
Tato zpráva byla zkontrolována na viry programem Avast Antivirus.
https://www.avast.com/antivirus
