### ISSUE TITLE
Add fullscreen support for HTML5 videos

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#224]
I successfully implemented some code to allow a BASIC! user to toggle fullscreen on HTML5 videos (tested successfully in the GW demo > Advanced > Videos).

Several stackoverflow posts were necessary to get it right (search was on "Android WebView html5 video fullscreen").

Change is very located: 2 new methods `onShowCustomView()` and `onHideCustomView` (22 lines overall) added in `engine.setWebChromeClient()`.

**Comment by jMarcS** [comment]
Released in Version 01.91, 2017/03/14.
