### ISSUE TITLE
: TTS.SPEAK do not support variables or functions as argument

### ISSUE THREAD

**Issue by JanuszChmiel** [RFO-BASIC/Basic#225]
Dear developers, : TTS.SPEAK do not allow users to send data to active speech engine if variable or function have been used as argument.
for example
a$ =time$
: TTS.SPEAK a$
will not speak. Would be possible to support atleast variable names which have ended with $ sign and time$ as a function?
Or it would be too complex to make this to work?
Thank you very much.

**Comment by olimaticer** [comment]
Hi Janusz,
TIME$ is in BASIC! not a system variable. In your example an emty string!
Try 
a$ = USING$("en_GB", "%tH:%<tM", int(time()))
TTS.SPEAK a$

And take a look in your system preferences.
Is the first loudness bar > 0?

Gregor

**Comment by JanuszChmiel** [comment]
Thank you very much for yours explanation and example.
And if I will add string to The a$
a$="good evening"
Will ttsspeak be able to speak The content of this variable?
Or which condition must variable meet so tts.speak will be able to speak it?
Thank You that you have included this speech function. It works great on 
Android 4.1.2 and also with Android 6.0. I have only thought that 
tts.speak method support only arguments when string is inserted directly 
between The quotes. And that it is inpossible to use some variable as 
argument.
Sure, I do not want to send array or bundle, I would cause system crash 
buffer overload. But atleast standard string and numeric variables.
Would you ensure, that tts.speak really support variables?
Thank you very much for yours time.

**Comment by olimaticer** [comment]
Hi Janusz,

Yes, normaly BASIC! will. I use string variables for TTS.SPEAK personally.
For testing it is a good idea to insert a PRINT a$ command.

a$="good evening"
PRINT "Contens of a$:[ "   a$   " ]"
TTS.SPEAK a$

And BASIC! do it with bundles, too.
bundleKey$ = "sentence1"
myWords$ = "I like bundles!"
BUNDLE.PUT bundlePointer, bundleKey$, myWords$

BUNDLE.TYPE bundlePointer, bundleKey$, bundleTyp$
IF bundleTyp$ = "S"
  BUNDLE.GET bundlePointer, bundleKey$, bundleContens$
  PRINT "Contens of bundleContens$:[ "   bundleContens$   " ]"
  TTS.SPEAK bundleContens$
ENDIF

Gregor

**Comment by JanuszChmiel** [comment]
Dear Gregor, thank you very much for given program examples. It is very useful for me. Very well done and I Am very sorry, that I have opened this issue. I will close it just now. And thank you very much for yours patience with me.
