### ISSUE TITLE
v01.91 compilation failure in About.java

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#232]
The Android BASIC! Compiler cannot compile BASIC! v01.91
Compilation stops with following error:

> Compile About.java with javac
> Error: compilation failed!
> ----------
> 1. ERROR in src/com/rfo/gwdemo/About.java
 (at line 48)
> 	public void onClick(View v) {
> 	            ^^^^^^^^^^^^^^^
> The method onClick(View) of type new > View.OnClickListener(){} must override a superclass method
> ----------
> 1 problem (1 error)

**Comment by jMarcS** [comment]
It does override a superclass method. Or rather, it implements an abstract method of an Interface, which amounts to the same thing. More importantly, it did compile when I built the v01.91 apk.

About.java is a new file in v01.91. Do your build process have a list of files that need to get their packages updated, or something similar?

**Comment by mougino** [comment]
You are right Marc, BASIC! v01.91 does compile with Java on PC, error only occurs on Android.
The Android Compiler lists all *.java files in the src folder and compiles each of them.
I'm going to do some google search to see what is wrong (I'm thinking maybe java 1.5 Vs 1.6 or something similar...)

**Comment by mougino** [comment]
Yes, this stackoverlow seems to point to a Java V5 issue:
http://stackoverflow.com/questions/9026918/onclicklistener-must-override-a-superclass-method

Some people say it's fixed by forcing Java 1.6 compliance, which -long story short- I cannot do on Android.
But apparently there's a workaround for Java 1.5: changing `new OnClickListener` by `new View.OnClickListener`... I am going to try that.

**Comment by jMarcS** [comment]
Perhaps "amounts to the same thing" is incorrect. The "@Override" annotation may not work on interfaces in all environments. It does on Eclipse and Android Studio, maybe not on the compiler you use on Android.

We use very few OnClickListeners -- we don't have a lot of UI -- and a quick check suggests they don't have @Override annotations. I'd guess Paul doesn't care much about annotations; Eclipse maybe did not have them when he started BASIC!.

**Comment by jMarcS** [comment]
I am planning to move BASIC! to Android Studio, but I am concerned that it will change the project structure so much that you cannot use it.

Annotations could be another problem. AS encourages some annotations that I never used in Eclipse.

**Comment by mougino** [comment]
`View.OnClickListener` did not solve the problem, adding `@Override` before `private void setupButton` didn't either, still digging...

About Android Studio, I agree, this would make the Android Compiler as it is today obsolete unfortunately :(
But we'll have to do it one day or another! I'll just have to get my hands dirty again to see how to compile an AS structure on an actual Android device. Maybe it has already been done? by AIDE or others?

Btw I did move BASIC! to Android Studio when I created basica, I had to make some changes before it could compile, but they were mixed with changes for basica (and I wasn't too cautious to keep BASIC! as is, I remember I had to raise SDK compatibility and get rid of older platforms typically 4.4...)

**Comment by jMarcS** [comment]
I'm sorry, I was not clear. Don't add an annotation. Delete the `@Override` before `onClick()`.

**Comment by mougino** [comment]
Right ;) I just did, waiting to test!

**Comment by jMarcS** [comment]
I can't wait -- we are already on daylight savings time, so it is 4:40 AM. In a few hours I'll come back and see how you fared!

**Comment by mougino** [comment]
It worked, but I got similar problems in Web.java apparently? There were changes there too?
I'll make an exhaustive list of changes that allow compilation on Android and I'll report.
Have a good night!

**Comment by jMarcS** [comment]
No changes in Web.java. But there is at least one `@Override` on an Interface method: `DialogInterface.OnDismissListener` is an Interface, and `onDismiss()` is annotated.

But in that case, how could you build v01.90? There is a mystery.

Good night! Er... I mean, bon matin!

**Comment by mougino** [comment]
Yes, I must have made the change manually in Web.java previously and forgot about it, shame on me...

All in all this allows compilation with Java 1.5 compatibility mode (so on Android device):
In *About.java* remove `@Override` before `public void onClick(View v)`
In *Web.java* remove `@Override` before `public void onDismiss(DialogInterface d)`

Will pushing those changes in GitHub repo have a negative impact on compilation > Java 1.6? (i.e. typically on PC)
I can keep doing that manually for the Compiler on the next versions anyway, not too much of a hassle...

**Comment by jMarcS** [comment]
No effect. The annotations are optional hints to the compiler and IDE so they can help the developer avoid mistakes.

**Comment by mougino** [comment]
Closing this issue as it's not a pure RFO BASIC! issue but rather an Android Compiler issue for which I found a workaround.
